//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuraManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CuraManager.Resources.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application language.
        /// </summary>
        internal static string ApplicationLanguage {
            get {
                return ResourceManager.GetString("ApplicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Theme.
        /// </summary>
        internal static string ApplicationTheme {
            get {
                return ResourceManager.GetString("ApplicationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive containing 3D Models.
        /// </summary>
        internal static string ArchiveContainingModels {
            get {
                return ResourceManager.GetString("ArchiveContainingModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        internal static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        internal static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to {0}.
        /// </summary>
        internal static string CopyTo {
            get {
                return ResourceManager.GetString("CopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new tag.
        /// </summary>
        internal static string CreateNewTag {
            get {
                return ResourceManager.GetString("CreateNewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        internal static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cura AppData location.
        /// </summary>
        internal static string CuraAppDataLocation {
            get {
                return ResourceManager.GetString("CuraAppDataLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cura ProgramFiles location.
        /// </summary>
        internal static string CuraProgramFilesLocation {
            get {
                return ResourceManager.GetString("CuraProgramFilesLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cura Project Files.
        /// </summary>
        internal static string CuraProjectFiles {
            get {
                return ResourceManager.GetString("CuraProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version.
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in the name of the new tag to create..
        /// </summary>
        internal static string Desc_CreateTag {
            get {
                return ResourceManager.GetString("Desc_CreateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in a new name for the file &quot;{0}&quot;..
        /// </summary>
        internal static string Desc_RenameFile {
            get {
                return ResourceManager.GetString("Desc_RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in a new name for the project &quot;{0}&quot;..
        /// </summary>
        internal static string Desc_RenameProject {
            get {
                return ResourceManager.GetString("Desc_RenameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed and published by Marc Schmidt.
        /// </summary>
        internal static string DevelopedAndPublished {
            get {
                return ResourceManager.GetString("DevelopedAndPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable all.
        /// </summary>
        internal static string DisableAll {
            get {
                return ResourceManager.GetString("DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download is completed!.
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        internal static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop some files here or use the plus button in the top right..
        /// </summary>
        internal static string DropFilesHereOrUseButton {
            get {
                return ResourceManager.GetString("DropFilesHereOrUseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable all.
        /// </summary>
        internal static string EnableAll {
            get {
                return ResourceManager.GetString("EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred!.
        /// </summary>
        internal static string ErrorHasOccurred {
            get {
                return ResourceManager.GetString("ErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again later..
        /// </summary>
        internal static string ErrorTryLater {
            get {
                return ResourceManager.GetString("ErrorTryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding files failed.
        /// </summary>
        internal static string Fail_AddMultipleFilesToProject {
            get {
                return ResourceManager.GetString("Fail_AddMultipleFilesToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding file failed.
        /// </summary>
        internal static string Fail_AddOneFileToProject {
            get {
                return ResourceManager.GetString("Fail_AddOneFileToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file failed.
        /// </summary>
        internal static string Fail_CopyFile {
            get {
                return ResourceManager.GetString("Fail_CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Cura project failed.
        /// </summary>
        internal static string Fail_CreateCuraProject {
            get {
                return ResourceManager.GetString("Fail_CreateCuraProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create project.
        /// </summary>
        internal static string Fail_CreateProject {
            get {
                return ResourceManager.GetString("Fail_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Project &quot;{0}&quot; failed.
        /// </summary>
        internal static string Fail_DeleteProject {
            get {
                return ResourceManager.GetString("Fail_DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading all models failed.
        /// </summary>
        internal static string Fail_ReloadModels {
            get {
                return ResourceManager.GetString("Fail_ReloadModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes failed.
        /// </summary>
        internal static string Fail_SaveChanges {
            get {
                return ResourceManager.GetString("Fail_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to add to project.
        /// </summary>
        internal static string FilesAddToProject {
            get {
                return ResourceManager.GetString("FilesAddToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install now.
        /// </summary>
        internal static string InstallNow {
            get {
                return ResourceManager.GetString("InstallNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Model Files.
        /// </summary>
        internal static string ModelFiles {
            get {
                return ResourceManager.GetString("ModelFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models to include.
        /// </summary>
        internal static string ModelsToInclude {
            get {
                return ResourceManager.GetString("ModelsToInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add at least one file to the project..
        /// </summary>
        internal static string Msg_AddAtLeastOneFileToProject {
            get {
                return ResourceManager.GetString("Msg_AddAtLeastOneFileToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected an archive file that does not exist..
        /// </summary>
        internal static string Msg_ArchiveDoesNotExist {
            get {
                return ResourceManager.GetString("Msg_ArchiveDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the file &quot;{0}&quot;?.
        /// </summary>
        internal static string Msg_ConfirmFileDeletion {
            get {
                return ResourceManager.GetString("Msg_ConfirmFileDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the project &quot;{0}&quot; with all its files and sub directories?.
        /// </summary>
        internal static string Msg_ConfirmProjectDeletion {
            get {
                return ResourceManager.GetString("Msg_ConfirmProjectDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cura paths are not configured correctly. Please make sure that under the configured AppData path a &quot;cura.cfg&quot;-file and under the ProgramFiles path the &quot;Cura.exe&quot;- or &quot;Ultimaker-Cura.exe&quot;-file exists..
        /// </summary>
        internal static string Msg_CuraPathsNotConfigured {
            get {
                return ResourceManager.GetString("Msg_CuraPathsNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new name..
        /// </summary>
        internal static string Msg_EnterNewName {
            get {
                return ResourceManager.GetString("Msg_EnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the name &quot;{0}&quot; already exists. Please choose another name..
        /// </summary>
        internal static string Msg_FileAlreadyExists {
            get {
                return ResourceManager.GetString("Msg_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to import in the clipboard..
        /// </summary>
        internal static string Msg_NothingValidInClipboard {
            get {
                return ResourceManager.GetString("Msg_NothingValidInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Print projects folder location&quot; is not configured or the directory does not exist. Please configure this setting correctly on the settings page..
        /// </summary>
        internal static string Msg_PrintProjectsFolderNotConfigured {
            get {
                return ResourceManager.GetString("Msg_PrintProjectsFolderNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project with the name &quot;{0}&quot; already exists. Please choose another name..
        /// </summary>
        internal static string Msg_ProjectAlreadyExists {
            get {
                return ResourceManager.GetString("Msg_ProjectAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the project failed: {0}.
        /// </summary>
        internal static string Msg_ProjectCreationFailed {
            get {
                return ResourceManager.GetString("Msg_ProjectCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an archive to import into a project..
        /// </summary>
        internal static string Msg_SelectArchiveToImport {
            get {
                return ResourceManager.GetString("Msg_SelectArchiveToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one 3D Model..
        /// </summary>
        internal static string Msg_SelectAtLeastOneModel {
            get {
                return ResourceManager.GetString("Msg_SelectAtLeastOneModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in a name for the project..
        /// </summary>
        internal static string Msg_SpecifyProjectName {
            get {
                return ResourceManager.GetString("Msg_SpecifyProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in a web address..
        /// </summary>
        internal static string Msg_TypeInUrl {
            get {
                return ResourceManager.GetString("Msg_TypeInUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made changes. Do you want to save them now?.
        /// </summary>
        internal static string Msg_UnsavedChanges {
            get {
                return ResourceManager.GetString("Msg_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided link is currently not supported..
        /// </summary>
        internal static string Msg_UnsupportedProjectPageUrl {
            get {
                return ResourceManager.GetString("Msg_UnsupportedProjectPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installed version is up to date..
        /// </summary>
        internal static string Msg_VersionUpToDate {
            get {
                return ResourceManager.GetString("Msg_VersionUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided address is not a valid thingiverse thing url. It needs to look something like this: https://www.thingiverse.com/thing:00000.
        /// </summary>
        internal static string Msg_WrongThingiverseUrl {
            get {
                return ResourceManager.GetString("Msg_WrongThingiverseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        internal static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available..
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Files.
        /// </summary>
        internal static string OtherFiles {
            get {
                return ResourceManager.GetString("OtherFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string PageHeader_About {
            get {
                return ResourceManager.GetString("PageHeader_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Projects.
        /// </summary>
        internal static string PageHeader_PrintProjects {
            get {
                return ResourceManager.GetString("PageHeader_PrintProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PageHeader_Settings {
            get {
                return ResourceManager.GetString("PageHeader_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print projects folder location.
        /// </summary>
        internal static string PrintProjectsFolderLocation {
            get {
                return ResourceManager.GetString("PrintProjectsFolderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding files to project....
        /// </summary>
        internal static string Prog_AddMultipleFilesToProject {
            get {
                return ResourceManager.GetString("Prog_AddMultipleFilesToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding file to project....
        /// </summary>
        internal static string Prog_AddOneFileToProject {
            get {
                return ResourceManager.GetString("Prog_AddOneFileToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file....
        /// </summary>
        internal static string Prog_CopyFile {
            get {
                return ResourceManager.GetString("Prog_CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Cura project....
        /// </summary>
        internal static string Prog_CreateCuraProject {
            get {
                return ResourceManager.GetString("Prog_CreateCuraProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating project &quot;{0}&quot;....
        /// </summary>
        internal static string Prog_CreateProject {
            get {
                return ResourceManager.GetString("Prog_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting project &quot;{0}&quot;....
        /// </summary>
        internal static string Prog_DeleteProject {
            get {
                return ResourceManager.GetString("Prog_DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading project data....
        /// </summary>
        internal static string Prog_LoadProjectData {
            get {
                return ResourceManager.GetString("Prog_LoadProjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading all models....
        /// </summary>
        internal static string Prog_ReloadModels {
            get {
                return ResourceManager.GetString("Prog_ReloadModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Filter.
        /// </summary>
        internal static string RefreshFilter {
            get {
                return ResourceManager.GetString("RefreshFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable Drive.
        /// </summary>
        internal static string RemovableDrive {
            get {
                return ResourceManager.GetString("RemovableDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred. Please send the following bug report to the developer:.
        /// </summary>
        internal static string SendErrorToDeveloper {
            get {
                return ResourceManager.GetString("SendErrorToDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download and install the newest version now?.
        /// </summary>
        internal static string ShouldDownloadUpdateNow {
            get {
                return ResourceManager.GetString("ShouldDownloadUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show archived projects.
        /// </summary>
        internal static string ShowArchivedProjects {
            get {
                return ResourceManager.GetString("ShowArchivedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show active projects.
        /// </summary>
        internal static string ShowNonArchivedProjects {
            get {
                return ResourceManager.GetString("ShowNonArchivedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the &quot;Create Project&quot; dialog when adding web links via clipboard or drag and drop. (If not activated the name of the downloaded file is automatically used).
        /// </summary>
        internal static string ShowWebDialogWhenAddingLink {
            get {
                return ResourceManager.GetString("ShowWebDialogWhenAddingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files have been added.
        /// </summary>
        internal static string Suc_AddMultipleFilesToProject {
            get {
                return ResourceManager.GetString("Suc_AddMultipleFilesToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was added.
        /// </summary>
        internal static string Suc_AddOneFileToProject {
            get {
                return ResourceManager.GetString("Suc_AddOneFileToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File have been copied.
        /// </summary>
        internal static string Suc_CopyFile {
            get {
                return ResourceManager.GetString("Suc_CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cura project have been created.
        /// </summary>
        internal static string Suc_CreateCuraProject {
            get {
                return ResourceManager.GetString("Suc_CreateCuraProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project was created.
        /// </summary>
        internal static string Suc_CreateProject {
            get {
                return ResourceManager.GetString("Suc_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &quot;{0}&quot; have been deleted.
        /// </summary>
        internal static string Suc_DeleteProject {
            get {
                return ResourceManager.GetString("Suc_DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All models have been reloaded.
        /// </summary>
        internal static string Suc_ReloadModels {
            get {
                return ResourceManager.GetString("Suc_ReloadModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes have been saved.
        /// </summary>
        internal static string Suc_SaveChanges {
            get {
                return ResourceManager.GetString("Suc_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes habe been revoked.
        /// </summary>
        internal static string Suc_UndoChanges {
            get {
                return ResourceManager.GetString("Suc_UndoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Cura Project.
        /// </summary>
        internal static string Title_CreateCuraProject {
            get {
                return ResourceManager.GetString("Title_CreateCuraProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        internal static string Title_CreateProject {
            get {
                return ResourceManager.GetString("Title_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tag.
        /// </summary>
        internal static string Title_CreateTag {
            get {
                return ResourceManager.GetString("Title_CreateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Title_Rename {
            get {
                return ResourceManager.GetString("Title_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file.
        /// </summary>
        internal static string Title_RenameFile {
            get {
                return ResourceManager.GetString("Title_RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename project.
        /// </summary>
        internal static string Title_RenameProject {
            get {
                return ResourceManager.GetString("Title_RenameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update version.
        /// </summary>
        internal static string Title_UpdateVersion {
            get {
                return ResourceManager.GetString("Title_UpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files to project.
        /// </summary>
        internal static string ToolTip_AddFilesToProject {
            get {
                return ResourceManager.GetString("ToolTip_AddFilesToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive project.
        /// </summary>
        internal static string ToolTip_ArchiveProject {
            get {
                return ResourceManager.GetString("ToolTip_ArchiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project from Clipboard....
        /// </summary>
        internal static string ToolTip_CreateProjectClipboard {
            get {
                return ResourceManager.GetString("ToolTip_CreateProjectClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project from Models....
        /// </summary>
        internal static string ToolTip_CreateProjectModels {
            get {
                return ResourceManager.GetString("ToolTip_CreateProjectModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project from the Web....
        /// </summary>
        internal static string ToolTip_CreateProjectWeb {
            get {
                return ResourceManager.GetString("ToolTip_CreateProjectWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project from ZIP....
        /// </summary>
        internal static string ToolTIp_CreateProjectZip {
            get {
                return ResourceManager.GetString("ToolTIp_CreateProjectZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the project.
        /// </summary>
        internal static string ToolTip_DeleteProject {
            get {
                return ResourceManager.GetString("ToolTip_DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string ToolTip_Filter {
            get {
                return ResourceManager.GetString("ToolTip_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Cura project.
        /// </summary>
        internal static string ToolTip_NewCuraProject {
            get {
                return ResourceManager.GetString("ToolTip_NewCuraProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project folder.
        /// </summary>
        internal static string ToolTip_OpenProjectFolder {
            get {
                return ResourceManager.GetString("ToolTip_OpenProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project page.
        /// </summary>
        internal static string ToolTip_OpenProjectPage {
            get {
                return ResourceManager.GetString("ToolTip_OpenProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload models.
        /// </summary>
        internal static string ToolTip_ReloadModels {
            get {
                return ResourceManager.GetString("ToolTip_ReloadModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename the project.
        /// </summary>
        internal static string ToolTip_RenameProject {
            get {
                return ResourceManager.GetString("ToolTip_RenameProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all changes.
        /// </summary>
        internal static string ToolTip_SaveAll {
            get {
                return ResourceManager.GetString("ToolTip_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take project out of archive.
        /// </summary>
        internal static string ToolTip_TakeProjectOutOfArchive {
            get {
                return ResourceManager.GetString("ToolTip_TakeProjectOutOfArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo all changes.
        /// </summary>
        internal static string ToolTip_UndoAll {
            get {
                return ResourceManager.GetString("ToolTip_UndoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now.
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download is complete and the update can now be started. Click &quot;Install now&quot; to start the update now!
        ///After pressing the button, the application is restarted..
        /// </summary>
        internal static string UpdateNowText {
            get {
                return ResourceManager.GetString("UpdateNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile and machine settings in Cura project before open. This prevents unwanted changes to your profiles when opening Cura projects..
        /// </summary>
        internal static string UpdateProfilesInCuraProjects {
            get {
                return ResourceManager.GetString("UpdateProfilesInCuraProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to project page (e.g.: Thingiverse).
        /// </summary>
        internal static string UrlToProjectPage {
            get {
                return ResourceManager.GetString("UrlToProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use operating system language.
        /// </summary>
        internal static string UseSystemLanguage {
            get {
                return ResourceManager.GetString("UseSystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP-Archive.
        /// </summary>
        internal static string ZipArchive {
            get {
                return ResourceManager.GetString("ZipArchive", resourceCulture);
            }
        }
    }
}
