//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuraManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CuraManager.Resources.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active slicer.
        /// </summary>
        internal static string ActiveSlicer {
            get {
                return ResourceManager.GetString("ActiveSlicer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag.
        /// </summary>
        internal static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick an existing tag or type a new one.
        /// </summary>
        internal static string AddTagDescription {
            get {
                return ResourceManager.GetString("AddTagDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application language.
        /// </summary>
        internal static string ApplicationLanguage {
            get {
                return ResourceManager.GetString("ApplicationLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string ApplicationSettings {
            get {
                return ResourceManager.GetString("ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Theme.
        /// </summary>
        internal static string ApplicationTheme {
            get {
                return ResourceManager.GetString("ApplicationTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive containing 3D Models.
        /// </summary>
        internal static string ArchiveContainingModels {
            get {
                return ResourceManager.GetString("ArchiveContainingModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        internal static string Changelog {
            get {
                return ResourceManager.GetString("Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates.
        /// </summary>
        internal static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to {0}.
        /// </summary>
        internal static string CopyTo {
            get {
                return ResourceManager.GetString("CopyTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to clipboard.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new tag.
        /// </summary>
        internal static string CreateNewTag {
            get {
                return ResourceManager.GetString("CreateNewTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        internal static string CreationTime {
            get {
                return ResourceManager.GetString("CreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version.
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Version.
        /// </summary>
        internal static string CustomSlicerVersion {
            get {
                return ResourceManager.GetString("CustomSlicerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in the name of the new tag to create..
        /// </summary>
        internal static string Desc_CreateTag {
            get {
                return ResourceManager.GetString("Desc_CreateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After launching Cura, type the project name into its name field using UI automation. Only affects Cura, only works on Windows, and can break when Cura changes its interface. This option will be removed in version 2.0..
        /// </summary>
        internal static string Desc_LegacyCuraProjectNaming {
            get {
                return ResourceManager.GetString("Desc_LegacyCuraProjectNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type in a new name for the file &quot;{0}&quot;..
        /// </summary>
        internal static string Desc_RenameFile {
            get {
                return ResourceManager.GetString("Desc_RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version found in the provided path.
        /// </summary>
        internal static string DetectedSlicerVersion {
            get {
                return ResourceManager.GetString("DetectedSlicerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed and published by Marc Schmidt.
        /// </summary>
        internal static string DevelopedAndPublished {
            get {
                return ResourceManager.GetString("DevelopedAndPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable all.
        /// </summary>
        internal static string DisableAll {
            get {
                return ResourceManager.GetString("DisableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download is completed!.
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        internal static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading.
        /// </summary>
        internal static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string DownloadLatestVersion {
            get {
                return ResourceManager.GetString("DownloadLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop some files here or use the plus button in the top right..
        /// </summary>
        internal static string DropFilesHereOrUseButton {
            get {
                return ResourceManager.GetString("DropFilesHereOrUseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable all.
        /// </summary>
        internal static string EnableAll {
            get {
                return ResourceManager.GetString("EnableAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the project name in Cura automatically.
        /// </summary>
        internal static string EnableLegacyCuraProjectNaming {
            get {
                return ResourceManager.GetString("EnableLegacyCuraProjectNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string EnableSlicer {
            get {
                return ResourceManager.GetString("EnableSlicer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred!.
        /// </summary>
        internal static string ErrorHasOccurred {
            get {
                return ResourceManager.GetString("ErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred. Please try again later..
        /// </summary>
        internal static string ErrorTryLater {
            get {
                return ResourceManager.GetString("ErrorTryLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding files failed.
        /// </summary>
        internal static string Fail_AddMultipleFilesToProject {
            get {
                return ResourceManager.GetString("Fail_AddMultipleFilesToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding file failed.
        /// </summary>
        internal static string Fail_AddOneFileToProject {
            get {
                return ResourceManager.GetString("Fail_AddOneFileToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file failed.
        /// </summary>
        internal static string Fail_CopyFile {
            get {
                return ResourceManager.GetString("Fail_CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create project.
        /// </summary>
        internal static string Fail_CreateProject {
            get {
                return ResourceManager.GetString("Fail_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0} project failed.
        /// </summary>
        internal static string Fail_CreateSlicerProject {
            get {
                return ResourceManager.GetString("Fail_CreateSlicerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting Project &quot;{0}&quot; failed.
        /// </summary>
        internal static string Fail_DeleteProject {
            get {
                return ResourceManager.GetString("Fail_DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading all models failed.
        /// </summary>
        internal static string Fail_ReloadModels {
            get {
                return ResourceManager.GetString("Fail_ReloadModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving changes failed.
        /// </summary>
        internal static string Fail_SaveChanges {
            get {
                return ResourceManager.GetString("Fail_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to add to project.
        /// </summary>
        internal static string FilesAddToProject {
            get {
                return ResourceManager.GetString("FilesAddToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install now.
        /// </summary>
        internal static string InstallNow {
            get {
                return ResourceManager.GetString("InstallNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest supported version.
        /// </summary>
        internal static string LatestSupportedSlicerVersion {
            get {
                return ResourceManager.GetString("LatestSupportedSlicerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest version.
        /// </summary>
        internal static string LatestVersion {
            get {
                return ResourceManager.GetString("LatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Features.
        /// </summary>
        internal static string LegacyFeatures {
            get {
                return ResourceManager.GetString("LegacyFeatures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new slicer project.
        /// </summary>
        internal static string MenuItem_NewSlicerProject {
            get {
                return ResourceManager.GetString("MenuItem_NewSlicerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Model Files.
        /// </summary>
        internal static string ModelFiles {
            get {
                return ResourceManager.GetString("ModelFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models to include.
        /// </summary>
        internal static string ModelsToInclude {
            get {
                return ResourceManager.GetString("ModelsToInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected an archive file that does not exist..
        /// </summary>
        internal static string Msg_ArchiveDoesNotExist {
            get {
                return ResourceManager.GetString("Msg_ArchiveDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the file &quot;{0}&quot;?.
        /// </summary>
        internal static string Msg_ConfirmFileDeletion {
            get {
                return ResourceManager.GetString("Msg_ConfirmFileDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the project &quot;{0}&quot; with all its files and sub directories?.
        /// </summary>
        internal static string Msg_ConfirmProjectDeletion {
            get {
                return ResourceManager.GetString("Msg_ConfirmProjectDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a new name..
        /// </summary>
        internal static string Msg_EnterNewName {
            get {
                return ResourceManager.GetString("Msg_EnterNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with the name &quot;{0}&quot; already exists. Please choose another name..
        /// </summary>
        internal static string Msg_FileAlreadyExists {
            get {
                return ResourceManager.GetString("Msg_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL.
        /// </summary>
        internal static string Msg_InvalidProjectUrl {
            get {
                return ResourceManager.GetString("Msg_InvalidProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No slicer is enabled. Enable one on the settings page to create projects..
        /// </summary>
        internal static string Msg_NoSlicerEnabled {
            get {
                return ResourceManager.GetString("Msg_NoSlicerEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to import in the clipboard..
        /// </summary>
        internal static string Msg_NothingValidInClipboard {
            get {
                return ResourceManager.GetString("Msg_NothingValidInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;Print projects folder location&quot; is not configured or the directory does not exist. Please configure this setting correctly on the settings page..
        /// </summary>
        internal static string Msg_PrintProjectsFolderNotConfigured {
            get {
                return ResourceManager.GetString("Msg_PrintProjectsFolderNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project with the name &quot;{0}&quot; already exists. Please choose another name..
        /// </summary>
        internal static string Msg_ProjectAlreadyExists {
            get {
                return ResourceManager.GetString("Msg_ProjectAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the project failed: {0}.
        /// </summary>
        internal static string Msg_ProjectCreationFailed {
            get {
                return ResourceManager.GetString("Msg_ProjectCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an archive to import into a project..
        /// </summary>
        internal static string Msg_SelectArchiveToImport {
            get {
                return ResourceManager.GetString("Msg_SelectArchiveToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one 3D Model..
        /// </summary>
        internal static string Msg_SelectAtLeastOneModel {
            get {
                return ResourceManager.GetString("Msg_SelectAtLeastOneModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The paths for {0} are not configured correctly. Please check the settings page..
        /// </summary>
        internal static string Msg_SlicerPathsNotConfigured {
            get {
                return ResourceManager.GetString("Msg_SlicerPathsNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in a name for the project..
        /// </summary>
        internal static string Msg_SpecifyProjectName {
            get {
                return ResourceManager.GetString("Msg_SpecifyProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type in a web address..
        /// </summary>
        internal static string Msg_TypeInUrl {
            get {
                return ResourceManager.GetString("Msg_TypeInUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have made changes. Do you want to save them now?.
        /// </summary>
        internal static string Msg_UnsavedChanges {
            get {
                return ResourceManager.GetString("Msg_UnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided link is currently not supported..
        /// </summary>
        internal static string Msg_UnsupportedProjectPageUrl {
            get {
                return ResourceManager.GetString("Msg_UnsupportedProjectPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The installed version is up to date..
        /// </summary>
        internal static string Msg_VersionUpToDate {
            get {
                return ResourceManager.GetString("Msg_VersionUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided address is not a valid thingiverse thing url. It needs to look something like this: https://www.thingiverse.com/thing:00000.
        /// </summary>
        internal static string Msg_WrongThingiverseUrl {
            get {
                return ResourceManager.GetString("Msg_WrongThingiverseUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name.
        /// </summary>
        internal static string NewName {
            get {
                return ResourceManager.GetString("NewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version.
        /// </summary>
        internal static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available..
        /// </summary>
        internal static string NewVersionAvailable {
            get {
                return ResourceManager.GetString("NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags assigned yet.
        /// </summary>
        internal static string NoTagsAssigned {
            get {
                return ResourceManager.GetString("NoTagsAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Files.
        /// </summary>
        internal static string OtherFiles {
            get {
                return ResourceManager.GetString("OtherFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string PageHeader_About {
            get {
                return ResourceManager.GetString("PageHeader_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Projects.
        /// </summary>
        internal static string PageHeader_PrintProjects {
            get {
                return ResourceManager.GetString("PageHeader_PrintProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PageHeader_Settings {
            get {
                return ResourceManager.GetString("PageHeader_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print projects folder location.
        /// </summary>
        internal static string PrintProjectsFolderLocation {
            get {
                return ResourceManager.GetString("PrintProjectsFolderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding files to project....
        /// </summary>
        internal static string Prog_AddMultipleFilesToProject {
            get {
                return ResourceManager.GetString("Prog_AddMultipleFilesToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding file to project....
        /// </summary>
        internal static string Prog_AddOneFileToProject {
            get {
                return ResourceManager.GetString("Prog_AddOneFileToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying file....
        /// </summary>
        internal static string Prog_CopyFile {
            get {
                return ResourceManager.GetString("Prog_CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating project &quot;{0}&quot;....
        /// </summary>
        internal static string Prog_CreateProject {
            get {
                return ResourceManager.GetString("Prog_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating {0} project....
        /// </summary>
        internal static string Prog_CreateSlicerProject {
            get {
                return ResourceManager.GetString("Prog_CreateSlicerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting project &quot;{0}&quot;....
        /// </summary>
        internal static string Prog_DeleteProject {
            get {
                return ResourceManager.GetString("Prog_DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading project data....
        /// </summary>
        internal static string Prog_LoadProjectData {
            get {
                return ResourceManager.GetString("Prog_LoadProjectData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloading all models....
        /// </summary>
        internal static string Prog_ReloadModels {
            get {
                return ResourceManager.GetString("Prog_ReloadModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project URL.
        /// </summary>
        internal static string ProjectUrl {
            get {
                return ResourceManager.GetString("ProjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Filter.
        /// </summary>
        internal static string RefreshFilter {
            get {
                return ResourceManager.GetString("RefreshFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable Drive.
        /// </summary>
        internal static string RemovableDrive {
            get {
                return ResourceManager.GetString("RemovableDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tag.
        /// </summary>
        internal static string RemoveTag {
            get {
                return ResourceManager.GetString("RemoveTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred. Please send the following bug report to the developer:.
        /// </summary>
        internal static string SendErrorToDeveloper {
            get {
                return ResourceManager.GetString("SendErrorToDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to download and install the newest version now?.
        /// </summary>
        internal static string ShouldDownloadUpdateNow {
            get {
                return ResourceManager.GetString("ShouldDownloadUpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show archived projects.
        /// </summary>
        internal static string ShowArchivedProjects {
            get {
                return ResourceManager.GetString("ShowArchivedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show active projects.
        /// </summary>
        internal static string ShowNonArchivedProjects {
            get {
                return ResourceManager.GetString("ShowNonArchivedProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the &quot;Create Project&quot; dialog when adding web links via clipboard or drag and drop. (If not activated the name of the downloaded file is automatically used).
        /// </summary>
        internal static string ShowWebDialogWhenAddingLink {
            get {
                return ResourceManager.GetString("ShowWebDialogWhenAddingLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppData location.
        /// </summary>
        internal static string SlicerAppDataLocation {
            get {
                return ResourceManager.GetString("SlicerAppDataLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation location.
        /// </summary>
        internal static string SlicerInstallLocation {
            get {
                return ResourceManager.GetString("SlicerInstallLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Project Files.
        /// </summary>
        internal static string SlicerProjectFiles {
            get {
                return ResourceManager.GetString("SlicerProjectFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string SlicerVersion {
            get {
                return ResourceManager.GetString("SlicerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files have been added.
        /// </summary>
        internal static string Suc_AddMultipleFilesToProject {
            get {
                return ResourceManager.GetString("Suc_AddMultipleFilesToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was added.
        /// </summary>
        internal static string Suc_AddOneFileToProject {
            get {
                return ResourceManager.GetString("Suc_AddOneFileToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File have been copied.
        /// </summary>
        internal static string Suc_CopyFile {
            get {
                return ResourceManager.GetString("Suc_CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project was created.
        /// </summary>
        internal static string Suc_CreateProject {
            get {
                return ResourceManager.GetString("Suc_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} project has been created.
        /// </summary>
        internal static string Suc_CreateSlicerProject {
            get {
                return ResourceManager.GetString("Suc_CreateSlicerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project &quot;{0}&quot; have been deleted.
        /// </summary>
        internal static string Suc_DeleteProject {
            get {
                return ResourceManager.GetString("Suc_DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All models have been reloaded.
        /// </summary>
        internal static string Suc_ReloadModels {
            get {
                return ResourceManager.GetString("Suc_ReloadModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes have been saved.
        /// </summary>
        internal static string Suc_SaveChanges {
            get {
                return ResourceManager.GetString("Suc_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes habe been revoked.
        /// </summary>
        internal static string Suc_UndoChanges {
            get {
                return ResourceManager.GetString("Suc_UndoChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        internal static string Title_CreateProject {
            get {
                return ResourceManager.GetString("Title_CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} Project.
        /// </summary>
        internal static string Title_CreateSlicerProject {
            get {
                return ResourceManager.GetString("Title_CreateSlicerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tag.
        /// </summary>
        internal static string Title_CreateTag {
            get {
                return ResourceManager.GetString("Title_CreateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit project.
        /// </summary>
        internal static string Title_EditProject {
            get {
                return ResourceManager.GetString("Title_EditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Title_Rename {
            get {
                return ResourceManager.GetString("Title_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename file.
        /// </summary>
        internal static string Title_RenameFile {
            get {
                return ResourceManager.GetString("Title_RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update version.
        /// </summary>
        internal static string Title_UpdateVersion {
            get {
                return ResourceManager.GetString("Title_UpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files to project.
        /// </summary>
        internal static string ToolTip_AddFilesToProject {
            get {
                return ResourceManager.GetString("ToolTip_AddFilesToProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive project.
        /// </summary>
        internal static string ToolTip_ArchiveProject {
            get {
                return ResourceManager.GetString("ToolTip_ArchiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project from Clipboard....
        /// </summary>
        internal static string ToolTip_CreateProjectClipboard {
            get {
                return ResourceManager.GetString("ToolTip_CreateProjectClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project from Models....
        /// </summary>
        internal static string ToolTip_CreateProjectModels {
            get {
                return ResourceManager.GetString("ToolTip_CreateProjectModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project from the Web....
        /// </summary>
        internal static string ToolTip_CreateProjectWeb {
            get {
                return ResourceManager.GetString("ToolTip_CreateProjectWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project from ZIP....
        /// </summary>
        internal static string ToolTIp_CreateProjectZip {
            get {
                return ResourceManager.GetString("ToolTIp_CreateProjectZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the project.
        /// </summary>
        internal static string ToolTip_DeleteProject {
            get {
                return ResourceManager.GetString("ToolTip_DeleteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the project.
        /// </summary>
        internal static string ToolTip_EditProject {
            get {
                return ResourceManager.GetString("ToolTip_EditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        internal static string ToolTip_Filter {
            get {
                return ResourceManager.GetString("ToolTip_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new {0} project.
        /// </summary>
        internal static string ToolTip_NewSlicerProject {
            get {
                return ResourceManager.GetString("ToolTip_NewSlicerProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project folder.
        /// </summary>
        internal static string ToolTip_OpenProjectFolder {
            get {
                return ResourceManager.GetString("ToolTip_OpenProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project page.
        /// </summary>
        internal static string ToolTip_OpenProjectPage {
            get {
                return ResourceManager.GetString("ToolTip_OpenProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload models.
        /// </summary>
        internal static string ToolTip_ReloadModels {
            get {
                return ResourceManager.GetString("ToolTip_ReloadModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save all changes.
        /// </summary>
        internal static string ToolTip_SaveAll {
            get {
                return ResourceManager.GetString("ToolTip_SaveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take project out of archive.
        /// </summary>
        internal static string ToolTip_TakeProjectOutOfArchive {
            get {
                return ResourceManager.GetString("ToolTip_TakeProjectOutOfArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo all changes.
        /// </summary>
        internal static string ToolTip_UndoAll {
            get {
                return ResourceManager.GetString("ToolTip_UndoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This version is not officially supported..
        /// </summary>
        internal static string UnsupportedSlicerVersion {
            get {
                return ResourceManager.GetString("UnsupportedSlicerVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now.
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The download is complete and the update can now be started. Click &quot;Install now&quot; to start the update now!
        ///After pressing the button, the application is restarted..
        /// </summary>
        internal static string UpdateNowText {
            get {
                return ResourceManager.GetString("UpdateNowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update profile and machine settings in the project before open. This prevents unwanted changes to your profiles when opening projects..
        /// </summary>
        internal static string UpdateProfilesInSlicerProjects {
            get {
                return ResourceManager.GetString("UpdateProfilesInSlicerProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to project page (e.g.: Thingiverse).
        /// </summary>
        internal static string UrlToProjectPage {
            get {
                return ResourceManager.GetString("UrlToProjectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to project page (optional).
        /// </summary>
        internal static string UrlToProjectPageOptional {
            get {
                return ResourceManager.GetString("UrlToProjectPageOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use operating system language.
        /// </summary>
        internal static string UseSystemLanguage {
            get {
                return ResourceManager.GetString("UseSystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version could not be detected using the provided path..
        /// </summary>
        internal static string Warn_NoSlicerVersionFound {
            get {
                return ResourceManager.GetString("Warn_NoSlicerVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version installed in the provided path is higher than the latest supported version. This might not be an issue, but be aware that there might be unforeseen issues when creating a new project. You can also check if there is a new version of CuraManager available that supports that version..
        /// </summary>
        internal static string Warn_SlicerVersionNotSupported {
            get {
                return ResourceManager.GetString("Warn_SlicerVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP-Archive.
        /// </summary>
        internal static string ZipArchive {
            get {
                return ResourceManager.GetString("ZipArchive", resourceCulture);
            }
        }
    }
}
